
version: '3'

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=FilmJunkiez
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin
  web:
    build: .
    command: ["wait-for-it", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db



