version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD} 

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] 
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - filmjunkiez-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5555:80"
    networks:
      - filmjunkiez-network

  django:
    build: .
    user: app
    volumes:
      - .:/app 
      - static_volume:/app/staticfiles  #
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - filmjunkiez-network
    environment:
      - SENTRY_DSN $FILM_JUNKIEZ_SENTRY_DSN
      - CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET
      - CLOUDINARY_URL=$CLOUDINARY_URL
      #- PORT=${PORT}
      #- DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DEV_DB_PORT}/${DATABASE_NAME}
      - PORT=5432
      - HEROKU_POSTGRESQL_AQUA_URLL=$HEROKU_POSTGRESQL_AQUA_URL
      - DOCKERIZED=1
networks:
  filmjunkiez-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume: #
