version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env  #${ENV_FILE_PATH} #.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] 
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - filmjunkiez-network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env   #${ENV_FILE_PATH}   # .env  
    ports:
      - "5555:80"
    networks:
      - filmjunkiez-network

  django:
    build: .
    user: myuser
    volumes:
      - .:/app
    working_dir: /app #/FilmJunkiez/filmjunkiez
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db:
      - condition: service_healthy
    networks:
      - filmjunkiez-network
    env_file:
      - .env  #${ENV_FILE_PATH}   #.env  
    environment:
      - PORT=${PORT}
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${PROD_DB_HOST}:${DEV_DB_PORT}/${DATABASE_NAME}
      - DOCKERIZED=1 
    
networks:
  filmjunkiez-network:
    driver: bridge

volumes:
  postgres_data:
