version: '3'

services:
  django:
    build: .
    user: myuser
    volumes:
      - .:/app
    working_dir: /filmjunkiez
    ports:
     - "${PORT}:${DJANGO_DB_PORT}"
    depends_on:
      - PROD_DB_HOST
    networks:
      - filmjunkiez-network
    environment:
      - PROD-DB_HOST=${PROD_DB_HOST}
      #- PORT=${PORT}
      - PORT=${DJANGO_DB_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DOCKERIZED=1
    #command: ["sh", "-c", "python manage.py print_db_params && python manage.py migrate"]
  PROD_DB_HOST:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      #- POSTGRES_HOST=${PROD_DB_HOST}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${DJANGO_DB_PORT}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - filmjunkiez-network

networks:
  filmjunkiez-network:
