version: '3'

services:
  django:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:${PORT}"]
    env_file:
      #- .env
      - /Users/gmworld/My Website/FilmJunkiez/.env
    volumes:
      - .:/code
    ports:
      - "${PORT}:${PORT}"
      
    depends_on:
      - db
    networks:
      - filmjunkiez-network
    environment:
      - DOCKERIZED=1
  db:
    image: postgres:latest
    #env_file: .env
    env_file: /Users/gmworld/My Website/FilmJunkiez/.env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - filmjunkiez-network

networks:
  filmjunkiez-network: