version: 2.1

orbs:
  heroku: circleci/heroku@1.2.1
  python: circleci/python@2.2.3

jobs:
  # Build and test the Docker image
  build-and-test:
    docker:
      - image: circleci/python:3.10-alpine

    steps:
      - checkout
      - run: sleep 60

      # Create and activate virtual environment
      - run: python -m venv venv
      - run: . venv/bin/activate

      # Install Python dependencies
      - run: pip install -r requirements.txt

      # Store cached dependencies for faster builds
      - save_cache:
          paths:
            - venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # Set DOCKERIZED environment variable
      - run: echo "DOCKERIZED=true" >> $BASH_ENV && source $BASH_ENV

      # Set PYTHONPATH for correct package resolution
      - run: echo "PYTHONPATH=$(pwd)/venv/lib/python3.12/site-packages" >> $BASH_ENV && source $BASH_ENV

      # Verify Django installation
      - run: python -m django --version

      # Run Pytest to test the Django application
      - run: pytest

      # Run database initialization and migrations
      - run: docker-compose run django python manage.py migrate

      # Setup remote Docker access for Heroku deployment
      - setup_remote_docker

      # Check DOCKER_LOGIN and DOCKER_USERNAME variables
      - run: echo $DOCKER_LOGIN
      - run: echo $DOCKER_USERNAME

      # Login to Docker Hub
      - run: docker login --username=${DOCKERHUB_USERNAME} --password-stdin ${DOCKER_LOGIN}

      # Build the Docker image first
      - run: docker build -t filmjunkiez .

      # Tag the Docker image
      - run: docker tag filmjunkiez "docker:${DOCKERHUB_USERNAME}/filmjunkiez"

      # Push the Docker image to Docker Hub
      - run: docker push "docker:${DOCKERHUB_USERNAME}/filmjunkiez"

  # Deploy the Docker image to Heroku
  deploy-to-heroku:
    docker:
      - image: circleci/python:3.10-alpine
    machine: true

    steps:
      - checkout

      # Install Heroku CLI and login with API key
      - run: sudo curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run: heroku login -r filmjunkiez --api-key $HEROKU_TOKEN

      # Push the Docker image to Heroku and release it
      - |
        heroku container:push -a filmjunkiez web
        heroku container:release -a filmjunkiez web