version: 2.1

jobs:
  build-and-test-django-app:
    docker:
      - image: circleci/python:3.9.7-buster
    environment:
      CI: true
    steps:
      - checkout
      - run: sleep 60
      - run:
          name: Remove existing venv directory
          command: rm -rf venv
      - run:
          name: Set up Python virtual environment
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: Install Python dependencies
          command: |
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Set DOCKERIZED variable
          command: echo "DOCKERIZED=true" >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Check sys.path
          command: python -c "import sys; print(sys.path)"
      - run:
          name: Set PYTHONPATH
          command: echo "PYTHONPATH=$(pwd)/venv/lib/python3.12/site-packages" >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Verify Django Installation
          command: python -m django --version
      - run:
          name: Check Directory Contents
          command: |
            pwd
            ls -la
            echo $PYTHONPATH
      - run:
          name: Production Database Migrations
          command: docker-compose run --env-file env django python manage.py migrate
  
      - run:
          name: Run Tests
          command: |
            export APP_EMAIL=$WEBSITE_EMAIL
            pytest

  deploy-to-heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: "Debug: Check DEPLOYED_APP_NAME"
          command: echo "DEPLOYED_APP_NAME=${DEPLOYED_APP_NAME}"

      - run:
          name: Build and push Docker image to Heroku
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a ${DEPLOYED_APP_NAME} web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a ${DEPLOYED_APP_NAME} web

      - run:
          name: Collect Static Files
          command: |
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku run -a ${DEPLOYED_APP_NAME} python manage.py collectstatic --noinput

workflows:
  version: 2
  build:
    jobs:
      - build-and-test-django-app
      - deploy-to-heroku:
          requires:
            - build-and-test-django-app
          filters:
            branches:
              only: master
