version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9.7-buster
    steps:
      - checkout
      - run: sleep 60
      - run:
          name: Remove existing venv directory
          command: rm -rf venv
      - run:
          name: Set up Python virtual environment
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: Install Python dependencies
          command: |
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Set DOCKERIZED variable
          command: echo "DOCKERIZED=true" >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Check sys.path
          command: python -c "import sys; print(sys.path)"    
      - run:
          name: Set PYTHONPATH
          command: echo "PYTHONPATH=$(pwd)/venv/lib/python3.12/site-packages" >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Verify Django Installation
          command: python -m django --version
      - run:
          name: Database Initialization
          command: docker run -e POSTGRES_PASSWORD=$DATABASE_PASSWORD -e POSTGRES_USER=$DATABASE_USER -e POSTGRES_DB=$DATABASE_NAME -e POSTGRES_HOST_AUTH_METHOD=md5 --name postgres -p 5432:5432 -d postgres:latest
      - run:
          name: Database Migrations
          #command: docker-compose run -e DOCKERIZED=1 django python manage.py migrate
          command: docker-compose run django python manage.py migrate 
      - run:
          name: Pytest
          command: pytest
      - setup_remote_docker
      - run:
          name: Check DOCKER_LOGIN
          command: echo $DOCKER_LOGIN
          no_output_timeout: 15s
      - run:
          name: Check DOCKER_USERNAME
          command: echo $DOCKER_USERNAME
          no_output_timeout: 15s
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_LOGIN | docker login --username=$DOCKER_USERNAME --password-stdin
      - run:
          name: Containerize
          command: |
            docker build -t filmjunkiez .
            docker tag filmjunkiez $DOCKER_USERNAME/filmjunkiez
            docker push $DOCKER_USERNAME/filmjunkiez

  deploy-to-heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a filmjunkiez web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a filmjunkiez web

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: "md5"

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
      - deploy-to-heroku:
          requires:
            - build-and-test
          filters:
            branches:
              only: master

