version: 2.1

jobs:
  build-and-test-app:
    docker:
      - image: docker/compose:latest
    working_directory: /Users/gmworld/My\ Website/FilmJunkiez
    steps:
      - run:
          name: Debugging
          command: |
            ls -la /app
            ls -la /app/.env
      - checkout
     
      # - run:
      #     name: Wait for Database
      #     command: |
      #       dockerize -wait tcp://db:5432 -timeout 1m -wait-retry-interval 10s -env /app/.env python /app/wait_for_db.py
      - run:
          name: Verify Docker Compose Configuration
          command: docker-compose config

      - run:
          name: Database Initialization
          command: docker-compose up -d db
      - run:
          name: Wait for Database to be Ready
          command: docker-compose run --rm django sh -c "echo Database is ready"

      - run:
          name: Network Accessibility
          command: docker-compose run --rm django python manage.py check_network_access

      - run:
          name: Print Environment Variables
          command: docker-compose run --rm django env

      - run:
          name: Build and Test
          command: docker-compose run --rm django pytest

      - run:
          name: Check CircleCI Configuration
          command: circleci config validate

      - run:
          name: Introduce Additional Logging
          command: docker-compose run --rm django python manage.py log_info

  deploy:
    docker:
      - image: docker/compose:latest

    steps:
      - checkout

      - run:
          name: Deploy to Heroku
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin registry.heroku.com
            docker-compose build
            docker-compose push
            heroku container:release web -a $DEPLOYED_APP_NAME

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test-app
      - deploy:
          requires:
            - build-and-test-app
