version: 2.1

jobs:
  build-and-test-django-app:
    docker:
      - image: circleci/python:3.9.7-buster
    steps:
      - checkout
      - run: sleep 60
      - run:
          name: Remove existing venv directory
          command: rm -rf venv
      - run:
          name: Set up Python virtual environment
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: Install Python dependencies
          command: |
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Set DOCKERIZED variable
          command: echo "DOCKERIZED=true" >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Check sys.path
          command: python -c "import sys; print(sys.path)"
      - run:
          name: Set PYTHONPATH
          command: echo "PYTHONPATH=$(pwd)/venv/lib/python3.12/site-packages" >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Verify Django Installation
          command: python -m django --version
      - run:
          name: Check Directory Contents
          command: |
            pwd
            ls -la
            echo $PYTHONPATH
      - run:
          name: Database Initialization
          command: sudo service postgresql stop && sudo service postgresql start ${DEV_DB_PORT}
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:${DEV_DB_PORT} -timeout 1m
      - run:
          name: Production Database Migrations
          command: docker-compose run --env-file env django python manage.py migrate
      - run:
          name: Pytest
          #command: pytest --ds=filmjunkiez.settings
          command: pytest

      - setup_remote_docker

      - run:
          name: Check DOCKER_LOGIN
          command: echo ${DOCKER_LOGIN}
          no_output_timeout: 15s

      - run:
          name: Check DOCKER_USERNAME
          command: echo ${DOCKER_USERNAME}
          no_output_timeout: 15s

      - run:
          name: Login to Docker Hub
          command: echo ${DOCKER_LOGIN} | docker login --username=${DOCKER_USERNAME} --password-stdin

      - run:
          name: Containerize
          command: |
            docker build -t filmjunkiez .
            docker tag filmjunkiez ${DOCKER_USERNAME}/filmjunkiez
            docker push ${DOCKER_USERNAME}/filmjunkiez

  deploy-to-heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: "Debug: Check DEPLOYED_APP_NAME"
          command: echo "DEPLOYED_APP_NAME=${DEPLOYED_APP_NAME}"

      - run:
          name: Build and push Docker image to Heroku
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a ${DEPLOYED_APP_NAME} web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a ${DEPLOYED_APP_NAME} web

workflows:
  version: 2
  build:
    jobs:
      - build-and-test-django-app
      - deploy-to-heroku:
          requires:
            - build-and-test-django-app
          filters:
            branches:
              only: master









