version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9.7-buster
    steps:
      - checkout
      - run: sleep 1000000
      - run:
          name: Remove existing venv directory
          command: rm -rf venv
      - run:
          name: Set up Python virtual environment
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Database Initialization
          command: docker run -e POSTGRES_PASSWORD=$DATABASE_PASSWORD -e POSTGRES_USER=$DATABASE_USER -e POSTGRES_DB=$DATABASE_NAME -e POSTGRES_HOST_AUTH_METHOD=md5 --name postgres -p 5432:5432 -d postgres:latest
      - run:
          name: Database Migrations
          command: python manage.py migrate
      - run:
          name: Pytest
          command: pytest
      - setup_remote_docker
      - run:
          name: Check DOCKER_LOGIN
          command: echo $DOCKER_LOGIN
          no_output_timeout: 15s
      - run:
          name: Check DOCKER_USERNAME
          command: echo $DOCKER_USERNAME
          no_output_timeout: 15s
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_LOGIN | docker login --username=$DOCKER_USERNAME --password-stdin
      - run:
          name: Containerize
          command: |
            docker build -t filmjunkiez .
            docker tag filmjunkiez $DOCKER_USERNAME/filmjunkiez
            docker push $DOCKER_USERNAME/filmjunkiez

workflows:
  version: 2
  build:
    jobs:
      - build-and-test:
          docker:
            - image: circleci/python:3.9.7-buster

      - deploy-to-heroku:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
