# Generated by Django 4.2.8 on 2024-02-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_film_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload an MP4 video file",
                null=True,
                upload_to="film_videos",
            ),
        ),
    ]
