# Generated by Django 4.2.8 on 2024-02-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_film_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="staticfilm/avatar.svg", null=True, upload_to=""
            ),
        ),
    ]
