# Generated by Django 4.2.8 on 2024-02-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload an MP4 video file",
                null=True,
                upload_to="film_videos",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
