# Generated by Django 4.2.8 on 2024-02-28 15:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_film_video_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload an MP4 video file",
                max_length=255,
                null=True,
            ),
        ),
    ]
