# Generated by Django 4.2.8 on 2024-01-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(name="user", table=None,),
    ]
