# Generated by Django 4.2.8 on 2024-02-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_film_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload an MP4 video file",
                null=True,
                upload_to="film_videos",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
