# Generated by Django 4.2.8 on 2024-01-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={},),
        migrations.AlterModelTable(name="user", table="auth_user",),
    ]
