# Generated by Django 4.2.8 on 2024-01-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="img/avatar.svg", null=True, upload_to=""),
        ),
    ]
