# Generated by Django 4.2.8 on 2024-01-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="static/img/avatar.svg", null=True, upload_to=""
            ),
        ),
    ]
