# Generated by Django 4.2.8 on 2024-03-01 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_film_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="host",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="film",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload an MP4 video file",
                null=True,
                upload_to="film_videos",
            ),
        ),
    ]
