# Generated by Django 4.2.8 on 2024-01-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
